services:
    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        user: 1000:1000
        volumes:
            - config:/config
            - cache:/cache
            - /mnt/media:/media
            - /mnt/erotica:/erotica
        restart: unless-stopped
        environment:
            - JELLYFIN_PublishedServerUrl=https://jellyfin.notclickable.com
        labels:
            traefik.enable: true
            traefik.http.routers.jellyfin.rule: Host(`jellyfin.notclickable.com`)
            traefik.http.routers.jellyfin.middlewares: tinyauth
            traefik.http.routers.jellyfin.tls.certresolver: cloudflare
            traefik.http.services.jellyfin.loadbalancer.server.port: 8096
        networks:
            - proxy

volumes:
    cache:
    config:

networks:
    proxy:
        external: true
