services:
    jellyfin:
        image: jellyfin/jellyfin:10.11.0
        container_name: jellyfin
        user: 1000:1000
        volumes:
            - config:/config
            - cache:/cache
            - /mnt/media:/media
            - /mnt/erotica:/erotica
        restart: unless-stopped
        environment:
            - JELLYFIN_PublishedServerUrl=https://jellyfin.notclickable.com
        networks:
            - caddy

volumes:
    cache:
    config:

networks:
    caddy:
        external: true
