services:
    starbase-80:
        image: jordanroher/starbase-80
        container_name: starbase-80
        restart: unless-stopped
        environment:
            - TITLE=Not Clickable
            - LOGO=/logo.png
            - NEWWINDOW=false
        volumes:
            - ./config.json:/app/src/config/config.json:ro
            - ./img/logo.png:/app/public/logo.png:ro
            - ./img/favicon.ico:/app/public/favicon.ico:ro
            - ./img:/app/public/img:ro
        labels:
            traefik.enable: true
            traefik.http.routers.starbase-80.rule: Host(`notclickable.com`) || Host(`www.notclickable.com`)
