services:
    starbase-80:
        image: jordanroher/starbase-80
        container_name: starbase-80
        restart: unless-stopped
        networks:
            - caddy
        environment:
            - TITLE=Not Clickable
            - LOGO=/logo.png
            - NEWWINDOW=false
        volumes:
            - ./config.json:/app/src/config/config.json:ro
            - ./img/logo.png:/app/public/logo.png:ro
            - ./img/favicon.ico:/app/public/favicon.ico:ro
            - ./img:/app/public/img:ro

networks:
    caddy:
        external: true
