services:
    gitlab:
        image: gitlab/gitlab-ce:latest
        container_name: gitlab
        restart: unless-stopped
        hostname: "gitlab.notclickable.com"
        environment:
            GITLAB_OMNIBUS_CONFIG: "from_file('/gitlab.rb')"
        ports:
            - 4209:22
        volumes:
            - config:/etc/gitlab
            - logs:/var/log/gitlab
            - data:/var/opt/gitlab
            - runner:/etc/gitlab-runner:ro
            - ./gitlab.rb:/gitlab.rb:ro
        shm_size: "256m"
        networks:
            - caddy

    runner:
        image: gitlab/gitlab-runner:latest
        container_name: gitlab-runner
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - runner:/etc/gitlab-runner
            - ./config.toml:/etc/gitlab-runner/config.toml
        networks:
            - caddy

volumes:
    config:
    logs:
    data:
    runner:

networks:
    caddy:
        external: true
