---
- name: Ensure required packages are installed
  apt:
    name:
      - git
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes

- name: Clone Apprise repository
  git:
    repo: "{{ apprise_repo }}"
    dest: "{{ apprise_clone_dest }}"
    version: master

- name: Create Apprise virtual environment
  command: python3 -m venv "{{ apprise_venv_dir }}"
  args:
    creates: "{{ apprise_venv_dir }}/bin/activate"

- name: Install Apprise in editable mode (inside venv)
  pip:
    chdir: "{{ apprise_clone_dest }}"
    editable: true
    name: .
    virtualenv: "{{ apprise_venv_dir }}"

- name: Verify Apprise installation (inside venv)
  command: "{{ apprise_venv_dir }}/bin/python -c 'import apprise'"
  register: apprise_check
  changed_when: false
  failed_when: apprise_check.rc != 0
