services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "/watchtower", "--health-check"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - traefik.enable=true
            - traefik.http.routers.watchtower.rule=Host(`watchtower.notclickable.com`)
            - "traefik.http.services.watchtower.loadbalancer.server.port=8080"
