services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "/watchtower", "--health-check"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
        env_file:
            - .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
