---
# Role: user_create
# Purpose: Create a non-sudo user and configure SSH key access

- name: Ensure user exists without sudo rights
  user:
    name: "{{ username }}"
    password: "{{ user_password }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Change user password to secure password
  user:
    name: "{{ username }}"
    password: "{{ user_secure_password }}"
    update_password: always

- name: Create .ssh directory for user
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0700'

- name: Add authorized public key for user
  copy:
    dest: "/home/{{ username }}/.ssh/authorized_keys"
    content: "{{ user_ssh_pubkey }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0600'