# List of volumes and their mount points (must match across scripts)
# Format: VOLUME_NAME:MOUNT_PATH
VOLUMES=(
  "caddy_config:/caddy/config"
  "caddy_data:/caddy/data"
  "freshrss_data:/freshrss/data"
  "freshrss_extensions:/freshrss/extensions"
  #"gitea_data:/gitea/data"
  #"gitea_db:/gitea/db"
  "grafana_storage:/grafana/storage"
  "lemmy_extra_themes:/lemmy/extra-themes"
  "lemmy_pictrs:/lemmy/pictrs"
  "lemmy_postgres:/lemmy/postgres"
  "lldap_lldap_data:/lldap/data"
  "n8n_app:/n8n/app"
  "n8n_db:/n8n/db"
  "pocket-id_data:/pocket-id/data"
  "jellyfin_config:/jellyfin/config"
  "jellyfin_cache:/jellyfin/cache"
  "mastodon_sidekiq:/mastodon/sidekiq"
  "mastodon_db:/mastodon/db"
  "mastodon_redis:/mastodon/redis"
  "mastodon_web:/mastodon/web"
  "calibre_config:/calibre/config"
  "ytptube_config:/ytptube/config"
  "audiobookshelf_config:/audiobookshelf/config"
  "audiobookshelf_metadata:/audiobookshelf/metadata"
)

BACKUP_PATH="/mnt/backup/rainhold/beacon"
