server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: nftables
    static_configs:
      - targets:
          - localhost
        labels:
          job: nftables
          __path__: /var/log/syslog
    pipeline_stages:
      - match:
          selector: '{job="nftables"}'
          stages:
            - regex:
                expression: "nftables-(input|forward|output): (?P<msg>.*)"
            - labels:
                chain: "$1"
  - job_name: caddy
    static_configs:
      - targets:
          - localhost
        labels:
          job: caddy
          __path__: /var/log/caddy/*log
          agent: caddy-promtail
    pipeline_stages:
      - json:
          expressions:
            duration: duration
            status: status
      - labels:
          duration:
          status:
