---
# Role: cloudflared
# Purpose: Install Cloudflared and configure a tunnel

- name: Ensure /usr/share/keyrings exists
  file:
    path: /usr/share/keyrings
    state: directory
    mode: "0755"

- name: Add Cloudflare GPG key
  ansible.builtin.get_url:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    dest: /usr/share/keyrings/cloudflare-main.gpg
    mode: "0644"

- name: Add Cloudflared apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main"
    filename: cloudflared
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install cloudflared
  ansible.builtin.apt:
    name: cloudflared
    state: present

- name: Create cloudflared config directory
  file:
    path: "/etc/cloudflared"
    state: directory
    mode: "0755"

- name: Deploy cloudflared configuration file
  template:
    src: config.yml.j2
    dest: "/etc/cloudflared/config.yml"
    mode: "0644"

- name: Check if cloudflared is already logged in
  stat:
    path: /etc/systemd/system/cloudflared.service
  register: cloudflared_service

- name: Login to Cloudflare Tunnel (using token)
  command: >
    cloudflared service install {{ cloudflared_token }}
  when: not cloudflared_service.stat.exists
  args:
    creates: /etc/systemd/system/cloudflared.service

- name: Enable and start cloudflared service
  systemd:
    name: cloudflared
    enabled: yes
    state: started
    daemon_reload: yes
