services:
    caddy:
        image: jordanroher/caddy-cloudflare-dns
        container_name: caddy
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        networks:
            - caddy
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
            - "2019:2019"
        volumes:
            - ./conf:/etc/caddy
            - data:/data
            - config:/config

volumes:
    data:
    config:

networks:
    caddy:
        external: true
