- name: Install postfix and mailutils
  apt:
    name:
      - postfix
      - mailutils
    state: present
    update_cache: yes

- name: Configure Postfix main settings for local delivery with virtual aliases
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
    backup: yes
  loop:
    - {
        regexp: "mydestination",
        line: "mydestination = $myhostname, localhost.$mydomain, localhost",
      }
    - { regexp: "home_mailbox", line: "home_mailbox = Maildir/" }
    - {
        regexp: "virtual_alias_maps",
        line: "virtual_alias_maps = regexp:/etc/postfix/virtual",
      }
    - {
        regexp: "smtpd_tls_security_level",
        line: "smtpd_tls_security_level = none",
      }
    - { regexp: "inet_interfaces", line: "inet_interfaces = all" }
    - { regexp: "inet_protocols", line: "inet_protocols = ipv4" }
    - { regexp: "mynetworks", line: "mynetworks = 0.0.0.0/0" }
    - {
        regexp: "smtpd_relay_restrictions",
        line: "smtpd_relay_restrictions = permit_mynetworks",
      }
    - {
        regexp: "smtpd_recipient_restrictions",
        line: "smtpd_recipient_restrictions = permit_mynetworks",
      }
    - {
        regexp: "smtpd_helo_restrictions",
        line: "smtpd_helo_restrictions = permit",
      }
    - {
        regexp: "smtpd_sender_restrictions",
        line: "smtpd_sender_restrictions = permit",
      }

- name: Ensure SMTP service is properly configured in master.cf
  lineinfile:
    path: /etc/postfix/master.cf
    regexp: "^smtp      inet  n       -       y       -       -       smtpd"
    line: "smtp      inet  n       -       y       -       -       smtpd"
    create: yes
    backup: yes

- name: Create virtual alias map to deliver all mail to single user
  copy:
    dest: /etc/postfix/virtual
    content: |
      /^.*@.*$/ {{ dovecot_mail_user }}
    backup: yes
  notify: Update postfix virtual maps

- name: Restart and enable Postfix
  service:
    name: postfix
    state: restarted
    enabled: yes

- name: Verify Postfix is listening on port 25
  wait_for:
    port: 25
    host: "0.0.0.0"
    timeout: 30
  ignore_errors: true

- name: Display network information for debugging
  debug:
    msg:
      - "Postfix configured to accept mail from ANY source (0.0.0.0/0)"
      - "All SMTP restrictions set to 'permit' - no authentication required"
      - "Test from anywhere: telnet {{ ansible_host }} 25"
      - "WARNING: This is an open mail relay for local delivery only"
