- name: Install postfix and mailutils
  apt:
    name:
      - postfix
      - mailutils
      - rsyslog
    state: present
    update_cache: yes

- name: Configure rsyslog for mail logging
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: "^#?mail\\.\\*"
    line: "mail.*                          /var/log/mail.log"
    create: yes
    backup: yes
  notify: restart rsyslog

- name: Check if syslog user exists
  getent:
    database: passwd
    key: syslog
  register: syslog_user_check
  ignore_errors: true

- name: Ensure mail.log file exists with proper permissions
  file:
    path: /var/log/mail.log
    state: touch
    owner: "{{ 'syslog' if syslog_user_check is succeeded else 'root' }}"
    group: "{{ 'adm' if syslog_user_check is succeeded else 'root' }}"
    mode: "0644"

- name: Configure Postfix to use syslog facility
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^syslog_facility"
    line: "syslog_facility = mail"
    create: yes
    backup: yes

- name: Enable verbose logging in Postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^syslog_name"
    line: "syslog_name = postfix"
    create: yes
    backup: yes

- name: Configure Postfix main settings for local delivery with virtual aliases
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
    backup: yes
  loop:
    - {
        regexp: "mydestination",
        line: "mydestination = $myhostname, localhost.$mydomain, localhost",
      }
    - { regexp: "home_mailbox", line: "home_mailbox = Maildir/" }
    - {
        regexp: "virtual_alias_maps",
        line: "virtual_alias_maps = regexp:/etc/postfix/virtual",
      }
    - {
        regexp: "smtpd_tls_security_level",
        line: "smtpd_tls_security_level = none",
      }
    - { regexp: "inet_interfaces", line: "inet_interfaces = all" }
    - { regexp: "inet_protocols", line: "inet_protocols = ipv4" }
    - { regexp: "mynetworks", line: "mynetworks = 0.0.0.0/0" }
    - {
        regexp: "smtpd_relay_restrictions",
        line: "smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination",
      }
    - {
        regexp: "smtpd_recipient_restrictions",
        line: "smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination",
      }
    - {
        regexp: "smtpd_helo_restrictions",
        line: "smtpd_helo_restrictions = permit",
      }
    - {
        regexp: "smtpd_sender_restrictions",
        line: "smtpd_sender_restrictions = permit",
      }
    - { regexp: "debug_peer_level", line: "debug_peer_level = 2" }
    - {
        regexp: "debug_peer_list",
        line: "debug_peer_list = 172.17.0.0/16, 100.64.0.0/10, 0.0.0.0/0",
      }
    - {
        regexp: "smtpd_banner",
        line: "smtpd_banner = $myhostname ESMTP Postfix (Debug Mode)",
      }

- name: Ensure SMTP service is properly configured in master.cf
  lineinfile:
    path: /etc/postfix/master.cf
    regexp: "^smtp      inet  n       -       y       -       -       smtpd"
    line: "smtp      inet  n       -       y       -       -       smtpd"
    create: yes
    backup: yes

- name: Create virtual alias map to deliver all mail to single user
  copy:
    dest: /etc/postfix/virtual
    content: |
      /^.*@.*$/ {{ dovecot_mail_user }}
    backup: yes
  notify: Update postfix virtual maps

- name: Restart and enable Postfix
  service:
    name: postfix
    state: restarted
    enabled: yes

- name: Restart rsyslog to enable mail logging
  service:
    name: rsyslog
    state: restarted
    enabled: yes
