- name: Install postfix and mailutils
  apt:
    name:
      - postfix
      - mailutils
    state: present
    update_cache: yes

- name: Configure Postfix main settings for local delivery with virtual aliases
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
    backup: yes
  loop:
    - {
        regexp: "mydestination",
        line: "mydestination = $myhostname, localhost.$mydomain, localhost",
      }
    - { regexp: "home_mailbox", line: "home_mailbox = Maildir/" }
    - {
        regexp: "virtual_alias_maps",
        line: "virtual_alias_maps = regexp:/etc/postfix/virtual",
      }
    - {
        regexp: "smtpd_tls_security_level",
        line: "smtpd_tls_security_level = none",
      }
    - { regexp: "inet_interfaces", line: "inet_interfaces = all" }
    - { regexp: "inet_protocols", line: "inet_protocols = ipv4" }
    - {
        regexp: "mynetworks",
        line: "mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 100.64.0.0/10",
      }
    - {
        regexp: "smtpd_relay_restrictions",
        line: "smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination",
      }
    - {
        regexp: "smtpd_recipient_restrictions",
        line: "smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination",
      }

- name: Create virtual alias map to deliver all mail to single user
  copy:
    dest: /etc/postfix/virtual
    content: |
      /^.*@.*$/ {{ dovecot_mail_user }}
    backup: yes
  notify: Update postfix virtual maps

- name: Restart and enable Postfix
  service:
    name: postfix
    state: restarted
    enabled: yes
