- name: Install postfix and mailutils
  apt:
    name:
      - postfix
      - mailutils
    state: present
    update_cache: yes

- name: Configure Postfix relayhost
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^relayhost ="
    line: "relayhost = [{{ mailrise_hostname }}]:8025"
    create: yes
    backup: yes

- name: Disable local delivery (force all mail through relayhost)
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^mydestination ="
    line: "mydestination ="
    create: yes
    backup: yes

- name: Configure Postfix SASL settings
  blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} ANSIBLE MANAGED SASL SETTINGS"
    block: |
      smtp_sasl_auth_enable = yes
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
      smtp_sasl_security_options = noanonymous
      smtp_tls_security_level = may

- name: Create sasl_passwd file
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: "0600"

- name: Generate hash db for sasl_passwd
  command: postmap /etc/postfix/sasl_passwd
  args:
    creates: /etc/postfix/sasl_passwd.db

- name: Configure Postfix transport map
  copy:
    dest: /etc/postfix/transport
    content: "* smtp:[{{ mailrise_hostname }}]:{{ mailrise_port }}"
    owner: root
    group: root
    mode: "0644"

- name: Generate hash db for transport map
  command: postmap /etc/postfix/transport
  args:
    creates: /etc/postfix/transport.db

- name: Configure Postfix to use transport map
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^transport_maps ="
    line: "transport_maps = hash:/etc/postfix/transport"
    create: yes
    backup: yes

- name: Restart Postfix
  service:
    name: postfix
    state: restarted
    enabled: yes
