- name: Install postfix and mailutils
  apt:
    name:
      - postfix
      - mailutils
    state: present
    update_cache: yes

- name: Enable local delivery
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^mydestination ="
    line: "mydestination = $myhostname, localhost.$mydomain, localhost"
    create: yes
    backup: yes

- name: Update smtpd_tls_security_level to none
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^smtpd_tls_security_level=may"
    line: "smtpd_tls_security_level=none"
    create: yes
    backup: yes

- name: Configure Postfix to deliver to Maildir
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^home_mailbox ="
    line: "home_mailbox = Maildir/"
    create: yes
    backup: yes

- name: Restart Postfix
  service:
    name: postfix
    state: restarted
    enabled: yes
