services:
    synapse:
        build:
            context: ../..
            dockerfile: docker/Dockerfile
        image: docker.io/matrixdotorg/synapse:latest
        container_name: synapse
        # Since synapse does not retry to connect to the database, restart upon
        # failure
        restart: unless-stopped
        # See the readme for a full documentation of the environment settings
        # NOTE: You must edit homeserver.yaml to use postgres, it defaults to sqlite
        environment:
            - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
        volumes:
            - files:/data
        depends_on:
            - db
        ports:
            - 4208:8448/tcp

    db:
        image: docker.io/postgres:15-alpine
        container_name: synapse_db
        env_file:
            - .env
        volumes:
            - schemas:/var/lib/postgresql/data

volumes:
    files:
    schemas:
