services:
    synapse:
        build:
            context: ../..
            dockerfile: docker/Dockerfile
        image: docker.io/matrixdotorg/synapse:latest
        container_name: synapse
        restart: unless-stopped
        environment:
            - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
        volumes:
            - files:/data
        depends_on:
            - db
        ports:
            - 4208:8008/tcp

    db:
        image: docker.io/postgres:15-alpine
        container_name: synapse_db
        env_file:
            - .env
        volumes:
            - schemas:/var/lib/postgresql/data

volumes:
    files:
    schemas:
