---
- name: Get list of subdirectories under stacks/{{ rainhold_stack }}/docker
  find:
    paths: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker"
    file_type: directory
    depth: 1
  register: rainhold_docker_dirs

- name: Check if compose.yml exists in each subdirectory
  stat:
    path: "{{ item.path }}/compose.yml"
  loop: "{{ rainhold_docker_dirs.files }}"
  register: compose_yml_stat

- name: Restart docker service in each subdirectory
  shell: docker compose down && docker compose up -d
  args:
    chdir: "{{ item.item.path }}"
  loop: "{{ compose_yml_stat.results }}"
  when: item.stat.exists
