---
- name: Get list of subdirectories under stacks/{{ rainhold_stack }}/docker
  find:
    paths: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker"
    file_type: directory
    depth: 1
  register: rainhold_docker_dirs

- name: Check if compose.yml exists in each subdirectory
  stat:
    path: "{{ item.path }}/compose.yml"
  loop: "{{ rainhold_docker_dirs.files }}"
  register: compose_yml_stat

- name: Bring down docker compose services in each subdirectory
  community.docker.docker_compose:
    project_src: "{{ item.item.path }}"
    state: absent
  loop: "{{ compose_yml_stat.results }}"
  when: item.stat.exists

- name: Bring up docker compose services in each subdirectory
  community.docker.docker_compose:
    project_src: "{{ item.item.path }}"
    state: present
    restarted: true
    pull: true
  loop: "{{ compose_yml_stat.results }}"
  when: item.stat.exists
