---
- name: Generate .env file for LLDAP
  template:
    src: lldap.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/lldap/.env"
    mode: "0600"
    owner: root
    group: root

- name: Generate .env file for Pocket ID
  template:
    src: pocket-id.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/pocket-id/.env"
    mode: "0600"
    owner: root
    group: root

- name: Generate .env file for Tinyauth
  template:
    src: tinyauth.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/tinyauth/.env"
    mode: "0600"
    owner: root
    group: root

- name: Generate .env file for Gitea
  template:
    src: gitea.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/gitea/.env"
    mode: "0600"
    owner: root
    group: root

- name: Generate .env file for Gitea's runner
  template:
    src: gitea.runner.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/gitea/.env.runner"
    mode: "0600"
    owner: root
    group: root

- name: Generate .env file for N8N
  template:
    src: n8n.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/n8n/.env"
    mode: "0600"
    owner: root
    group: root

- name: Ensure Caddy conf folder exists
  file:
    path: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/caddy/conf/"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Generate Caddyfile for Caddy
  template:
    src: caddyfile.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/caddy/conf/Caddyfile"
    mode: "0644"
    owner: root
    group: root

- name: Generate config file for Mailrise
  template:
    src: mailrise.conf.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/mailrise/mailrise.conf"
    mode: "0644"
    owner: root
    group: root

- name: Generate config for Lemmy
  template:
    src: lemmy.hjson.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/lemmy/lemmy.hjson"
    mode: "0644"
    owner: root
    group: root

- name: Generate env for Lemmy
  template:
    src: lemmy.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/lemmy/.env"
    mode: "0600"
    owner: root
    group: root

- name: Generate env.pictrs for Lemmy
  template:
    src: lemmy.env.pictrs.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/lemmy/.env.pictrs"
    mode: "0600"
    owner: root
    group: root

- name: Generate env.postgres for Lemmy
  template:
    src: lemmy.env.postgres.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/lemmy/.env.postgres"
    mode: "0600"
    owner: root
    group: root

- name: Generate env.postfix for Lemmy
  template:
    src: lemmy.env.postfix.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/lemmy/.env.postfix"
    mode: "0600"
    owner: root
    group: root

- name: Generate env for Miniflux
  template:
    src: miniflux.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/miniflux/.env"
    mode: "0600"
    owner: root
    group: root

- name: Generate env for Miniflux database
  template:
    src: miniflux.env.db.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/miniflux/.env.db"
    mode: "0600"
    owner: root
    group: root

- name: Generate env for Grafana
  template:
    src: grafana.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/grafana/.env"
    mode: "0600"
    owner: root
    group: root

- name: Generate prometheus.yml for Grafana stack
  template:
    src: prometheus.yml.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/grafana/prometheus.yml"
    mode: "0644"
    owner: root
    group: root

- name: Generate promtail config for Grafana stack
  template:
    src: promtail-config.yml.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/grafana/promtail-config.yml"
    mode: "0644"
    owner: root
    group: root

- name: Generate env for Mastodon
  template:
    src: mastodon.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/mastodon/.env"
    mode: "0600"
    owner: root
    group: root

- name: Generate env for Mastodon Postgres
  template:
    src: mastodon.env.postgres.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/mastodon/.env.postgres"
    mode: "0600"
    owner: root
    group: root

- name: Generate env for Watchtower
  template:
    src: watchtower.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/watchtower/.env"
    mode: "0600"
    owner: root
    group: root

- name: Generate env for Vaultwarden
  template:
    src: vaultwarden.env.j2
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/vaultwarden/.env"
    mode: "0600"
    owner: root
    group: root
