---
- name: Ensure destination directory exists
  file:
    path: "{{ rainhold_dest }}"
    state: directory
    mode: '0755'

- name: Clone rainhold repository
  git:
    repo: "{{ rainhold_repo }}"
    dest: "{{ rainhold_dest }}"
    version: main
    force: yes