services:
    ytptube:
        image: ghcr.io/arabcoders/ytptube:latest
        container_name: ytptube
        restart: unless-stopped
        volumes:
            - config:/config
            - /mnt/media/video/YouTube:/downloads
        tmpfs:
            - /tmp
        ports:
            - 4221:8081
        networks:
            - caddy

volumes:
    config:

networks:
    caddy:
        external: true
