services:
    ytptube:
        user: "1000:1000"
        image: ghcr.io/arabcoders/ytptube:latest
        container_name: ytptube
        restart: unless-stopped
        ports:
            - 4221:8081
        volumes:
            - config:/config
            - /mnt/media/video/YouTube:/downloads
        tmpfs:
            - /tmp
        labels:
            traefik.enable: true
            traefik.http.routers.ytptube.rule: Host(`ytptube.notclickable.com`)
            traefik.http.routers.ytptube.middlewares: tinyauth@docker
            traefik.http.routers.ytptube.tls.certresolver: cloudflare
            traefik.http.services.ytptube.loadbalancer.server.port: 8081
        networks:
            - proxy

volumes:
    config:

networks:
    proxy:
        external: true
