services:
    ytptube:
        user: "1000:1000"
        image: ghcr.io/arabcoders/ytptube:latest
        container_name: ytptube
        restart: unless-stopped
        ports:
            - 4221:8081
        volumes:
            - config:/config
            - /mnt/media/video/YouTube:/downloads
        tmpfs:
            - /tmp

volumes:
    config:
