---
# Generate a self-signed TLS certificate for Mailrise
- name: Ensure directory for Mailrise TLS cert exists
  file:
    path: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/mailrise"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Generate self-signed TLS certificate for Mailrise
  community.crypto.x509_certificate:
    path: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/mailrise/mailrise.crt"
    privatekey_path: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/mailrise/mailrise.key"
    csr_path: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/mailrise/mailrise.csr"
    provider: selfsigned
    state: present
