---
# Role: ssh_hardening
# Purpose: Disable password login and root SSH access

- name: Disable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication\s+.*'
    line: 'PasswordAuthentication no'

- name: Fully disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin\s+.*'
    line: 'PermitRootLogin no'
    state: present

- name: Restart SSH daemon
  service:
    name: ssh
    state: restarted