services:
    calibre:
        image: linuxserver/calibre-web:latest
        container_name: calibre
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Los_Angeles
            - DOCKER_MODS=linuxserver/mods:universal-calibre
            - OAUTHLIB_RELAX_TOKEN_SCOPE=1
        volumes:
            - config:/config
            - /mnt/media/books:/books
        restart: unless-stopped
        networks:
            - caddy

volumes:
    config:

networks:
    caddy:
        external: true
