---
# Wildduck email server setup role

- name: Clone Wildduck dockerized repository
  git:
    repo: https://github.com/nodemailer/wildduck-dockerized
    dest: /etc/wildduck-dockerized
    version: master
    force: yes

- name: Make setup script executable
  file:
    path: /etc/wildduck-dockerized/setup.sh
    mode: "0755"

- name: Ensure target config directory exists
  file:
    path: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/config"
    state: directory
    mode: "0755"
    recurse: yes

- name: Ensure python3-pexpect is installed for expect module
  apt:
    name: python3-pexpect
    state: present
    update_cache: yes
  become: true

- name: Run setup script with expect to handle interactive prompts
  expect:
    command: sudo ./setup.sh mail.notclickable.com notclickable.com true
    responses:
      "set up self-signed certs for development\\? \\(Y/n\\)": "y"
      "set up the DNS\\? \\[Y/n\\]": "n"
    timeout: 300
  args:
    chdir: /etc/wildduck-dockerized
  register: setup_result
  become: true

- name: Debug setup script output
  debug:
    var: setup_result.stdout_lines

- name: Copy config directory to target
  copy:
    src: /etc/wildduck-dockerized/config-generated/config-generated
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/config"
    remote_src: yes
    directory_mode: yes
    mode: preserve

- name: Copy certs directory to target
  copy:
    src: /etc/wildduck-dockerized/config-generated/certs
    dest: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/certs"
    remote_src: yes
    directory_mode: yes
    mode: preserve

- name: Ensure proper permissions on certs files
  file:
    path: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/certs"
    state: directory
    mode: "0755"
    recurse: yes

- name: Move files from certs/certs to certs
  shell: |
    mv {{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/certs/certs/* {{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/certs/ 2>/dev/null || true
  ignore_errors: true

- name: Remove certs/certs directory if it exists
  file:
    path: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/certs/certs"
    state: absent

- name: Ensure proper permissions on config files
  file:
    path: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/config"
    state: directory
    mode: "0755"
    recurse: yes

- name: Move files from config/config-generated to config
  shell: |
    mv {{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/config/config-generated/* {{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/config/ 2>/dev/null || true
  ignore_errors: true

- name: Remove config/config-generated directory if it exists
  file:
    path: "{{ rainhold_dest }}/stacks/{{ rainhold_stack }}/docker/wildduck/config/config-generated"
    state: absent
