services:
    email-page:
        image: jordanroher/email-page:latest
        container_name: email-page
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - data:/etc/email-page/data
        networks:
            - caddy

volumes:
    data:

networks:
    caddy:
        external: true
