---
- name: Install cifs-utils
  apt:
    name: cifs-utils
    state: present
  become: true

- name: Ensure mount points exist
  file:
    path: "{{ item.mount_point }}"
    state: directory
    mode: "0755"
  loop: "{{ network_shares }}"
  loop_control:
    label: "{{ item.mount_point }}"
  become: true

- name: Create SMB credentials file (shared)
  copy:
    dest: "/root/.smbcredentials_networkshare"
    content: |
      username={{ network_share_username }}
      password={{ network_share_password }}
    mode: "0600"
  become: true

- name: Ensure fstab entries for network shares
  lineinfile:
    path: /etc/fstab
    line: "//{{ network_share_host }}/{{ item.name }} {{ item.mount_point }} cifs vers=3.0,credentials=/root/.smbcredentials_networkshare,uid={{ item.uid | default(1000) }},gid={{ item.gid | default(1000) }} 0 0"
    state: present
    create: yes
    backup: yes
  loop: "{{ network_shares }}"
  loop_control:
    label: "{{ item.mount_point }}"
  become: true

- name: Run systemctl daemon-reload
  command: systemctl daemon-reload
  become: true

- name: Run mount -a to activate all fstab mounts
  command: mount -a
  become: true
