---
- name: Install cifs-utils
  apt:
    name: cifs-utils
    state: present
  become: true

- name: Ensure mount point exists
  file:
    path: "{{ network_share_mount_point }}"
    state: directory
    mode: "0755"
  become: true

- name: Create SMB credentials file
  copy:
    dest: "/root/.smbcredentials"
    content: |
      username={{ network_share_username }}
      password={{ network_share_password }}
    mode: "0600"
  become: true

- name: Ensure fstab entry for network share
  lineinfile:
    path: /etc/fstab
    line: "//{{ network_share_host }}/{{ network_share_name }} {{ network_share_mount_point }} cifs vers=3.0,credentials=/root/.smbcredentials,uid={{ network_share_uid | default(1000) }},gid={{ network_share_gid | default(1000) }} 0 0"
    state: present
    create: yes
    backup: yes
  become: true

- name: Run systemctl daemon-reload
  command: systemctl daemon-reload
  become: true

- name: Run mount -a to activate all fstab mounts
  command: mount -a
  become: true
