services:
    traefik:
        image: traefik:3.4
        container_name: traefik
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - ./traefik.yml:/etc/traefik/traefik.yml
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - letsencrypt:/letsencrypt

volumes:
    letsencrypt:
