services:
    traefik:
        image: traefik:3.4
        container_name: traefik
        ports:
            - 80:80
            - 443:443
            - 587:587
            - 8080:8080
        env_file:
            - .env
        volumes:
            - ./traefik.yml:/etc/traefik/traefik.yml:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - letsencrypt:/letsencrypt
        networks:
            - proxy

volumes:
    letsencrypt:

networks:
    proxy:
        external: true
