services:
    storyden:
        image: ghcr.io/southclaws/storyden
        container_name: storyden
        restart: unless-stopped
        environment:
            - PUBLIC_WEB_ADDRESS=https://storyden.notclickable.com
            - PUBLIC_API_ADDRESS=https://storyden.notclickable.com
        volumes:
            - data:/storyden/data
        networks:
            - caddy
volumes:
    data:

networks:
    caddy:
        external: true
