services:
    miniflux:
        image: miniflux/miniflux:latest
        container_name: miniflux
        healthcheck:
            test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
        env_file:
            - .env
        restart: unless-stopped
        networks:
            - caddy
        depends_on:
            miniflux-db:
                condition: service_healthy

    miniflux-db:
        image: postgres:17-alpine
        container_name: miniflux-db
        env_file:
            - .env.db
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "miniflux"]
            interval: 10s
            start_period: 30s
        networks:
            - caddy
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db:

networks:
    caddy:
        external: true
