[api]
port = 8080
host = "0.0.0.0"
secure = false

[log]
level = "silly"

[dbs]
# mongodb connection string for the main database
mongo = "mongodb://mongo:27017/wildduck-test"

# redis connection string
redis = "redis://redis:6379/13"

dbname = "wildduck-test"

[imap]
port = 9993
host = "127.0.0.1"

[lmtp]
enabled = true
port = 2424
