services:
    audiobookshelf:
        image: ghcr.io/advplyr/audiobookshelf:latest
        container_name: audiobookshelf
        volumes:
            - /mnt/media/audiobooks:/audiobooks
            - /mnt/media/podcasts:/podcasts
            - config:/config
            - metadata:/metadata
        environment:
            - TZ=America/Los_Angeles
        restart: unless-stopped
        labels:
            - traefik.enable=true
            - traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.notclickable.com`)

volumes:
    config:
    metadata:
