services:
    audiobookshelf:
        image: ghcr.io/advplyr/audiobookshelf:latest
        container_name: audiobookshelf
        ports:
            - 4222:80
        volumes:
            - /mnt/media/audiobooks:/audiobooks
            - /mnt/media/podcasts:/podcasts
            - config:/config
            - metadata:/metadata
        environment:
            - TZ=America/Los_Angeles
        restart: unless-stopped

volumes:
    config:
    metadata:
