---
# Role: tailscale
# Purpose: Install and connect Tailscale with a pre-generated auth key

- name: Fetch Tailscale archive signing key
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg"
    dest: "/usr/share/keyrings/tailscale-archive-keyring.gpg"
    mode: "0644"
    force: true

- name: Install Tailscale APT source list
  ansible.builtin.get_url:
    url: "https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list"
    dest: "/etc/apt/sources.list.d/tailscale.list"
    mode: "0644"
    force: true

- name: Refresh APT cache to pick up the new repo
  ansible.builtin.apt:
    update_cache: true

- name: Install Tailscale
  apt:
    name: tailscale
    state: present

- name: Connect to Tailscale using auth key
  command: "tailscale up --authkey={{ tailscale_authkey }}"
  register: tailscale_result
  changed_when: "'Logged in' in tailscale_result.stdout or 'Success' in tailscale_result.stdout"
  no_log: true  # Hide key in output
  become: true