---
# tasks file for nftables-logging
- name: Ensure inet table exists
  become: true
  command: nft add table inet filter
  register: nft_table_result
  failed_when: false
  changed_when: nft_table_result.rc == 0

- name: Ensure input chain exists
  become: true
  command: nft add chain inet filter input '{ type filter hook input priority 0; }'
  register: nft_input_chain_result
  failed_when: false
  changed_when: nft_input_chain_result.rc == 0

- name: Ensure forward chain exists
  become: true
  command: nft add chain inet filter forward '{ type filter hook forward priority 0; }'
  register: nft_forward_chain_result
  failed_when: false
  changed_when: nft_forward_chain_result.rc == 0

- name: Ensure output chain exists
  become: true
  command: nft add chain inet filter output '{ type filter hook output priority 0; }'
  register: nft_output_chain_result
  failed_when: false
  changed_when: nft_output_chain_result.rc == 0

- name: Ensure nftables logging is enabled for dropped packets only
  become: true
  command: >
    nft add rule inet filter input counter drop log prefix "nftables-input-drop"
  ignore_errors: true

- name: Ensure nftables logging is enabled for suspicious connections
  become: true
  command: >
    nft add rule inet filter input tcp flags syn tcp dport 22 limit rate 10/minute log prefix "nftables-ssh-attempt"
  ignore_errors: true
