---
# Role: updates
# Purpose: Set up automatic security updates

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present

- name: Enable unattended-upgrades
  command: dpkg-reconfigure --priority=low unattended-upgrades
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Configure 20auto-upgrades using template
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
