---
# Role: Caddy
# Purpose: Install and configure Caddy web server

- name: Install Caddy APT dependencies
  apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - curl
    state: present
    update_cache: yes

- name: Add Caddy GPG key
  ansible.builtin.shell: |
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

- name: Add Caddy APT repository
  copy:
    dest: /etc/apt/sources.list.d/caddy-stable.list
    content: |
      deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian all main

- name: Update apt cache after adding Caddy repo
  apt:
    update_cache: yes

- name: Install Caddy
  apt:
    name: caddy
    state: present

- name: Deploy Caddyfile
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: 0644

- name: Reload Caddy to apply config
  systemd:
    name: caddy
    state: reloaded
    enabled: yes