services:
    mailrise:
        image: yoryan/mailrise:latest
        container_name: mailrise
        restart: unless-stopped
        volumes:
            - ./mailrise.conf:/etc/mailrise.conf:ro
        labels:
            traefik.tcp.routers.mailrise.rule: "HostSNI(`*`)"
            traefik.tcp.routers.mailrise.tls: "true"
            traefik.tcp.routers.mailrise.tls.certresolver: letsencrypt
            traefik.tcp.routers.mailrise.tls.domains[0].main: "mailrise.notclickable.com"
            traefik.tcp.routers.mailrise.tls.domains[0].sans: ""
            traefik.tcp.routers.mailrise.entrypoints: "mailsecure"
