services:
    mailrise:
        image: yoryan/mailrise:latest
        container_name: mailrise
        restart: unless-stopped
        volumes:
            - ./mailrise.conf:/etc/mailrise.conf:ro
        ports:
            - 465:465
