# Database configuration

# MongoDB connection string
mongo = "mongodb://mongo:27017/zone-mta"

# Database name for ZoneMTA data in MongoDB. In most cases it should be the same as in the connection string
sender = "zone-mta"

# Redis connection information
[redis]
host = "redis"
port = 6379
db = 2
